portfolio/src/Entity/Languages.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LanguagesRepository")
 */
class Languages
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer")
     */
    private $Level;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="languages")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->Level;
    }

    public function setLevel(int $Level): self
    {
        $this->Level = $Level;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

portfolio/src/Entity/Skills.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SkillsRepository")
 */
class Skills
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hardSkill = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $softSkill = false;

    /**
     * @ORM\Column(type="integer")
     */
    private $completion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="skills")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getHardSkill(): ?bool
    {
        return $this->hardSkill;
    }

    public function setHardSkill(bool $hardSkill): self
    {
        $this->hardSkill = $hardSkill;

        return $this;
    }

    public function getSoftSkill(): ?bool
    {
        return $this->softSkill;
    }

    public function setSoftSkill(bool $softSkill): self
    {
        $this->softSkill = $softSkill;

        return $this;
    }

    public function getCompletion(): ?int
    {
        return $this->completion;
    }

    public function setCompletion(int $completion): self
    {
        $this->completion = $completion;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

portfolio/templates/index_parts/about.html.twig
{% for user in users %}
<div class="container">
    <div class="card" data-aos="zoom-in" data-aos-offset="10" data-aos-duration="500">
        <div class="row">
            <div class="col-lg-6 col-md-12">
                <div class="card-body">
                    <div class="h4 mt-0 title">About me</div>
                    <p>{{ user.paragraph }}</p>
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="card-body">
                    <div class="h4 mt-0 title">Informations</div>
                    <div class="row">
                        <div class="col-sm-4"><strong class="text-uppercase">Age:</strong></div>
                        <div class="col-sm-8">{{ user.age }}</div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4"><strong class="text-uppercase"><a data-toggle="modal" data-target="#exampleModalScrollable">
                                    <i class="fa fa-at fa-2x"></i></a></strong>
                        </div>
                        <div class="col-sm-8">
                            <a data-toggle="modal" data-target="#exampleModalScrollable">
                                {{ user.email }}
                            </a>
                        </div>


                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4"><strong class="text-uppercase"><i class="fa fa-phone fa-2x"></i></strong></div>
                        <div class="col-sm-8"><a href="tel:{{ user.phone }}">(+33) {{ user.phone }}</a></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4"><strong class="text-uppercase"><i class="fab fa-github fa-2x"></i></strong></div>
                        <div class="col-sm-8"><a href="{{ user.github }}" target="_blank">{{ user.github }}</a></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4"><strong class="text-uppercase"><i class="fab fa-linkedin fa-2x"></i></strong></div>
                        <div class="col-sm-8"><a href="{{ user.linkedin }}" target="_blank">{{ user.linkedin }}</a></div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-sm-4"><strong class="text-uppercase">Languages:</strong></div>
                        <div class="col-sm-8">
                            {% for language in languages %}
                                <p>{{ language.name }}</p>
                                <div class="progress">
                                    <div class="progress-bar bg-dark" role="progressbar" style="width: {{ language.level }}%" aria-valuenow="{{ language.level }}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalScrollableTitle">Contact me</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ include('contact/_form.html.twig') }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

portfolio/templates/index_parts/diplomas.html.twig
<div class="container">
    <div class="h4 text-center mb-4 title white">Diplomas</div>
    {% for diploma in diplomas %}
    {% if loop.index % 2 == 0 %}
        <div class="card" {#data-aos="fade-right"#}>
        {% else %}
        <div class="card" {#data-aos="fade-left"#}>
        {% endif %}
                <div class="row no-gutters">
                    <div class="col-md-3 bg-secondary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500" style="height: auto;">
                        <div class="card-body">
                            <p>From {{ diploma.startDate | date('m/Y') }} to {{ diploma.endDate | date('m/Y') }}</p>
                            <div class="h5">{{ diploma.location | title}}</div>
                        </div>
                    </div>
                    <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500" style="height: auto;">
                        <div class="card-body">
                            <div class="h5">{{ diploma.name | title }}</div>
                            <p>{{ diploma.specialty | title }}</p>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}
</div>

portfolio/templates/index_parts/experiences.html.twig
<div class="container">
    <div class="h4 text-center mb-4 title white">Professional Experiences</div>
    {% for experience in experiences %}
        {% if loop.index % 2 == 0 %}
            <div class="card mb-4" {#data-aos="fade-right"#}>
        {% else %}
            <div class="card mb-4" {#data-aos="fade-left"#}>
        {% endif %}
                <div class="row no-gutters">
                    <div class="col-md-3 bg-secondary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500" style="height: auto;">
                        <div class="card-body">
                            <p>From {{ experience.startDate | date('m/Y') }} to {{ experience.endDate | date('m/Y') }}</p>
                            <div class="h5">{{ experience.societyName }}</div>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="card-body" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
                            <div class="h5">{{ experience.title }}</div>
                            <p>{{ experience.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}
</div>

portfolio/templates/index_parts/hardskills.html.twig
    <div class="container">
        <div class="h4 text-center mb-4 title white">Hard Skills</div>
        <div class="card" data-aos="fade-left">
            <div class="card-body">
                <div class="row d-flex justify-content-right">
                {% for skill in skills %}
                    {% if skill.hardSkill %}

                            <div class="col-md-3">
                                <div class="progress-container progress-primary">{{ skill.name | title }}</div>
                            </div>
                            <div class="col-md-3">
                                <div class="progress">
                                    <div class="progress-bar bg-dark" role="progressbar" style="width: {{ skill.completion }}%" aria-valuenow="{{ skill.completion }}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>

                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

portfolio/templates/index_parts/navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top mb-5" data-aos="fade-down" data-aos-duration="10000">
    <a class="navbar-brand" href="#">Portfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#about">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#projects">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#experiences">Experiences</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Skills
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#skill1">Soft Skills</a>
                    <a class="dropdown-item" href="#skill2">Hard Skills</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#diplomas">Diplomas</a>
            </li>
        </ul>
    </div>
</nav>

portfolio/templates/index_parts/projects.html.twig
    <div class="h4 mt-0 text-center white">Projects</div>
    <div class="card-transparent" data-aos="fade-right">
        <div class="card-body">

            <div class="container mt-5" style="width:50vw">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox" style=" width:100%; height: 20rem !important;">
                        {% for project in projects %}

                        {% if loop.index == 1 %}
                        <div class="carousel-item active" data-interval="1000000">
                            {% else %}
                            <div class="carousel-item" data-interval="1000000">
                                {% endif %}
                                <img src="{{ asset('uploads/' ~ project.screenshot) }}" class="d-block w-100">
                                <div class="carousel-caption d-none d-md-block captionCarousel">
                                    <h5><a class="carouselLink" data-toggle="collapse" href="#collapse{{ project.id }}" role="button" aria-expanded="false" aria-controls="collapseExample">{{ project.name | title }}</a></h5>
                                    <p>From {{ project.startDate | date('m/Y')}} to {{ project.endDate | date('m/Y') }}</p>
                                </div>
                            </div>
                            <div class="collapse" id="collapse{{ project.id }}">
                                <div class="card card-body text-center">
                                    <h3>{{ project.name | title }}</h3>
                                    <p>{{ project.description | title }}</p>
                                    <a href="{{ project.link }}"><i class="fa fa-link"></i></a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

portfolio/templates/index_parts/softskills.html.twig
    <div class="container">
        <div class="h4 text-center mb-4 title white">Soft Skills</div>
        <div class="card" data-aos="fade-right" data-aos-offset="10">
            <div class="card-body">
                <div class="row d-flex justify-content-right">
                {% for skill in skills %}
                    {% if skill.softSkill %}

                            <div class="col-md-3">
                                <div class="progress-container progress-primary">{{ skill.name | title }}</div>
                            </div>
                            <div class="col-md-3">
                                <div class="progress">
                                    <div class="progress-bar bg-dark" role="progressbar" style="width: {{ skill.completion }}%" aria-valuenow="{{ skill.completion }}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>

                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
    </div>